/**
 * Generates the self-hosted font bundle for the Storybook site from the installed
 * @fontsource packages: copies the needed woff2 subsets into apps/radix-storybook/public/fonts/
 * and assembles public/fonts.css from fontsource's own @font-face declarations (authoritative
 * unicode-range values), rewriting URLs to /fonts/ and 'Inter Variable' → 'Inter'.
 *
 * The output is committed; re-run after bumping @fontsource-variable/inter or
 * @fontsource/jetbrains-mono:
 *
 *   node tools/scripts/fonts/generate.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const outDir = path.join(root, 'apps/radix-storybook/public/fonts');
fs.mkdirSync(outDir, { recursive: true });

const SUBSETS = ['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext'];

const sources = [
    { pkg: '@fontsource-variable/inter', css: ['wght.css', 'wght-italic.css'] },
    { pkg: '@fontsource/jetbrains-mono', css: ['400.css', '700.css'] }
];

const blocks = [];
const copied = new Set();

for (const { pkg, css } of sources) {
    const pkgDir = path.join(root, 'node_modules', pkg);
    for (const cssFile of css) {
        const content = fs.readFileSync(path.join(pkgDir, cssFile), 'utf8');
        // split into comment+@font-face blocks
        const faceRe = /\/\*[^*]*\*\/\s*@font-face\s*\{[\s\S]*?\}/g;
        for (const block of content.match(faceRe) ?? []) {
            // comment format: /* inter-latin-ext-wght-italic */ or /* jetbrains-mono-latin-400-normal */
            const comment = /\/\* ([\w-]+) \*\//.exec(block)?.[1] ?? '';
            const subset = comment.replace(/^(inter|jetbrains-mono)-/, '').replace(/-(wght|\d+)-(normal|italic)$/, '');
            if (!SUBSETS.includes(subset)) continue;
            // keep only woff2 src lines, rewrite url to /fonts/
            const files = [...block.matchAll(/url\(\.\/files\/([\w.-]+?\.woff2)\)\s*format\('([\w-]+)'\)/g)];
            if (!files.length) continue;
            const src = files.map(([, file, fmt]) => {
                fs.copyFileSync(path.join(pkgDir, 'files', file), path.join(outDir, file));
                copied.add(file);
                return `url(/fonts/${file}) format('${fmt}')`;
            });
            const cleaned = block
                .replace(/src:[\s\S]*?;/, `src: ${src.join(', ')};`)
                .replace(/font-display:\s*\w+;/, 'font-display: swap;')
                // the site theme references plain 'Inter' (tailwind.css, themes.ts)
                .replace("font-family: 'Inter Variable';", "font-family: 'Inter';");
            blocks.push(cleaned);
        }
    }
}

const header = `/*
 * Self-hosted fonts — generated by tools/scripts/fonts/generate.mjs from @fontsource packages.
 * Do not edit by hand; re-run the script after bumping the font dependencies.
 * Served from / via Storybook staticDirs; linked from preview-head.html and manager-head.html.
 * Inter: variable wght (100-900) normal + italic. JetBrains Mono: 400 + 700.
 * Subsets: ${SUBSETS.join(', ')}.
 */\n\n`;

fs.writeFileSync(path.join(root, 'apps/radix-storybook/public/fonts.css'), header + blocks.join('\n\n') + '\n');
console.log(`fonts.css: ${blocks.length} @font-face blocks, ${copied.size} woff2 files copied`);
console.log([...copied].join('\n'));
