# Dependabot options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    # Ignores any major updates
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      linters:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
          - '@angular-eslint/*'
          - 'prettier*'
          - 'stylelint*'
          - '@commitlint/*'
      nx:
        patterns:
          - 'nx'
          - '@nx/*'
          - '@swc*'
      angular:
        patterns:
          - '@angular/*'
          - 'rxjs'
          - 'zone.js'
          - '@angular-devkit/*'
          - '@schematics/angular'
          - 'ng-packagr'
      jest:
        patterns:
          - 'jest*'
          - 'ts-jest'
      radix:
        patterns:
          - '@radix*'
      storybook:
        patterns:
          - '@storybook/*'
