name: Setup pnpm
description: Common setup steps used by our workflows

inputs:
  node-version:
    description: The version of node.js
    required: false
    default: '20.18.1'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - uses: nrwl/nx-set-shas@v4

    - name: Print Environment Info
      run: npx nx report
      shell: bash
