packages:
  - "apps/radix-docs/**"
  - "packages/**"
  - "!**/dist/**"
allowBuilds:
  '@compodoc/compodoc': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@shikijs/core@4.2.0'
  - '@shikijs/engine-javascript@4.2.0'
  - '@shikijs/engine-oniguruma@4.2.0'
  - '@shikijs/langs@4.2.0'
  - '@shikijs/primitive@4.2.0'
  - '@shikijs/themes@4.2.0'
  - '@shikijs/transformers@4.2.0'
  - '@shikijs/types@4.2.0'
  - astro@6.4.3
  - shiki@4.2.0
  - '@nx/angular@23.1.0-beta.1'
  - '@nx/cypress@23.1.0-beta.1'
  - '@nx/devkit@23.1.0-beta.1'
  - '@nx/docker@23.1.0-beta.1'
  - '@nx/esbuild@23.1.0-beta.1'
  - '@nx/eslint@23.1.0-beta.1'
  - '@nx/jest@23.1.0-beta.1'
  - '@nx/js@23.1.0-beta.1'
  - '@nx/module-federation@23.1.0-beta.1'
  - '@nx/node@23.1.0-beta.1'
  - '@nx/nx-darwin-arm64@23.1.0-beta.1'
  - '@nx/nx-darwin-x64@23.1.0-beta.1'
  - '@nx/nx-freebsd-x64@23.1.0-beta.1'
  - '@nx/nx-linux-arm-gnueabihf@23.1.0-beta.1'
  - '@nx/nx-linux-arm64-gnu@23.1.0-beta.1'
  - '@nx/nx-linux-arm64-musl@23.1.0-beta.1'
  - '@nx/nx-linux-x64-gnu@23.1.0-beta.1'
  - '@nx/nx-linux-x64-musl@23.1.0-beta.1'
  - '@nx/nx-win32-arm64-msvc@23.1.0-beta.1'
  - '@nx/nx-win32-x64-msvc@23.1.0-beta.1'
  - '@nx/plugin@23.1.0-beta.1'
  - '@nx/rspack@23.1.0-beta.1'
  - '@nx/storybook@23.1.0-beta.1'
  - '@nx/vite@23.1.0-beta.1'
  - '@nx/vitest@23.1.0-beta.1'
  - '@nx/web@23.1.0-beta.1'
  - '@nx/webpack@23.1.0-beta.1'
  - '@nx/workspace@23.1.0-beta.1'
  - nx@23.1.0-beta.1
