import { RdxTransitionStatus } from '@radix-ng/primitives/core';
import { Align, RdxPopperAnchorElement, Side } from '@radix-ng/primitives/popper';

/** Relative ordering hint for a toast. `high` toasts are announced assertively. */
export type RdxToastPriority = 'low' | 'high';

/** Action-button options carried on a toast and read back by the consumer (e.g. an "Undo" button). */
export interface RdxToastActionProps {
    /** Visible button label. */
    label?: string;
    /** Invoked when the action button is clicked. */
    onClick?: (event: MouseEvent) => void;
}

/**
 * Anchoring options for a toast rendered through `rdxToastPositioner` instead of the stack. The
 * `anchor` is any popper-compatible reference (element, `ElementRef`, or virtual element).
 */
export interface RdxToastPositionerProps {
    anchor: RdxPopperAnchorElement;
    side?: Side;
    sideOffset?: number;
    align?: Align;
    alignOffset?: number;
}

/**
 * A single toast in the {@link RdxToastManager} queue. `id` is stable for the toast's lifetime;
 * `transitionStatus` reflects the enter/leave animation phase (mirrors Base UI's transition system).
 */
export interface RdxToastObject<Data = unknown> {
    /** Stable id; generated by the manager when omitted from {@link RdxToastAddOptions}. */
    id: string;
    /** Short heading text. */
    title?: string;
    /** Supporting body text. */
    description?: string;
    /** Caller-defined category (e.g. `'success' | 'error'`) for styling/branching. */
    type?: string;
    /** Auto-dismiss delay in ms. `0` (or a negative value) disables auto-dismiss. */
    timeout?: number;
    /** Announcement priority. `high` → `role="alert"` (assertive); `low` → `role="status"`. */
    priority?: RdxToastPriority;
    /** Arbitrary caller payload, surfaced back to templates/handlers. */
    data?: Data;
    /** Enter/leave phase, set by the manager while a toast mounts or is being removed. */
    transitionStatus?: RdxTransitionStatus;
    /** Set while a `promise()` toast is awaiting its source promise. */
    loading?: boolean;
    /** Action-button options surfaced to the template. */
    actionProps?: RdxToastActionProps;
    /** Anchoring options; when present the toast is positioned with `rdxToastPositioner`. */
    positionerProps?: RdxToastPositionerProps;
    /** Bump on an upsert (same `id`) to replay the enter animation. */
    updateKey?: number | string;
    /** Invoked when the toast is dismissed (by timeout, swipe, or `close()`). */
    onClose?: () => void;
    /** Invoked after the leave animation completes and the toast leaves the queue. */
    onRemove?: () => void;
}

/** Options accepted by {@link RdxToastManager.add} / {@link RdxToastManager.update}. */
export interface RdxToastAddOptions<Data = unknown> {
    id?: string;
    title?: string;
    description?: string;
    type?: string;
    timeout?: number;
    priority?: RdxToastPriority;
    data?: Data;
    /** Marks the toast as pending (used by `promise()`); pending toasts skip auto-dismiss. */
    loading?: boolean;
    actionProps?: RdxToastActionProps;
    positionerProps?: RdxToastPositionerProps;
    updateKey?: number | string;
    onClose?: () => void;
    onRemove?: () => void;
}

/** Per-state copy used by {@link RdxToastManager.promise}. */
export interface RdxToastPromiseOptions<Value = unknown, Data = unknown> {
    loading: RdxToastAddOptions<Data> | string;
    success: RdxToastAddOptions<Data> | string | ((value: Value) => RdxToastAddOptions<Data> | string);
    error: RdxToastAddOptions<Data> | string | ((error: unknown) => RdxToastAddOptions<Data> | string);
}
