name: 'Chromatic'

on:
  push:
    branches:
      - main

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Run Chromatic
        uses: chromaui/action@98132da0fca2211fb41b3af7b49ce85176007851 # v17.8.0
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
